vars:
    temp_address: 10.0.5.88
    dc_address: 10.0.5.5
    dc_netmask_cidr: 24
    dc_gateway: 10.0.5.2
    dc_hostname: 'blue1-dc'
    domain_name: "blue1.local"
    local_admin: '.\Administrator'
    temp_password: ''
    dc_password: ''
    recovery_password: ''
    upstream_dns_1: 10.0.5.3
    upstream_dns_2: 10.0.5.4
    reverse_dns_zone: "10.0.5.0/24"
    ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org"
