# Sources: https://madlabber.wordpress.com/2019/09/08/creating-a-new-active-directory-forest-with-ansible/

- name: Create new Active-Directory Domain & Forest
  hosts: localhost
  vars:
    temp_address: 10.0.5.88
    dc_address: 10.0.5.5
    dc_netmask_cidr: 24
    dc_gateway: 10.0.5.2
    dc_hostname: 'blue1-dc'
    domain_name: "blue1.local"
    local_admin: '.\Administrator'
    temp_password: ''
    dc_password: ''
    recovery_password: ''
    upstream_dns_1: 10.0.5.3
    upstream_dns_2: 10.0.5.4
    reverse_dns_zone: "10.0.5.0/24"
    ntp_servers: "0.us.pool.ntp.org,1.us.pool.ntp.org"
  gather_facts: no

tasks:
- name: Add host to Ansible inventory
  add_host:
    name: '{{ temp_address }}'
    ansible_user: '{{ local_admin }}'
    ansible_password: '{{ temp_password }}'
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_port: 5986
- name: Wait for system to become reachable over WinRM
  wait_for_connection:
    timeout: 900
  delegate_to: '{{ temp_address }}'